### ISSUE TITLE
generator-babel name

### ISSUE THREAD

**Issue by iamstarkov** [gios/generator-babel#2]
As far as you renamed this package to generator-boot-babel, would you mind to delegate me 'generator-babel' name on npm?

**Comment by iamstarkov** [comment]
You can take a look at my work here https://github.com/iamstarkov/generator-babel-init#readme

**Comment by iamstarkov** [comment]
@gios would you mind to delegate me `generator-babel` name on npm?

**Comment by gios** [comment]
I deleted `generator-babel` package from npm. This name should be available for registration.

**Comment by iamstarkov** [comment]
@gios thank you. its alive https://www.npmjs.com/package/generator-babel
